name: Shane Statz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74549
title: Shane Statz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcf2e8'
    - '#6f7b7d'
    - '#6d4e12'
    - '#d2b960'
  brandStrength: 0.0764055922627449
  lightness: 0.3125
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
