name: Shane Statz
favicon: null
layout_spectrum: 0.55866
typography_spectrum: 0.25
title: Shane Statz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcf2e8'
    - '#6f7b7d'
    - '#6d4e12'
    - '#d2b960'
  brandStrength: 0.8319167322479188
  lightness: 0.4742061332799494
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
