layout_spectrum: 0.2283221345860511
typography_spectrum: 0.8285800705198199
color:
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  brandStrength: 0.13492142246104777
  lightness: 0.803338821278885
  saturation: 0.06742546451278031
  rhythmicContrast: 0.6833596606738865
name: Shane Statz
favicon: null
title: Shane Statz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
