layout_spectrum: 0.24853227264247835
typography_spectrum: 0.01444745366461575
color:
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  brandStrength: 0.32809057529084384
  lightness: 0.2723734846804291
  saturation: 0.9102736636996269
  rhythmicContrast: 0.11792157148011029
name: Shane Statz
favicon: null
title: Shane Statz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
