name: Shane Statz
favicon: null
layout_spectrum: 0.9704552674666047
typography_spectrum: 0.23965023853816092
title: Shane Statz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcf2e8'
    - '#6f7b7d'
    - '#6d4e12'
    - '#d2b960'
  brandStrength: 0.9632474156096578
  lightness: 0.3115666371304542
  saturation: 0.5828139814548194
  rhythmicContrast: 0.14006863627582788
purpose: []
