layout_spectrum: 0.6373320680577308
typography_spectrum: 0.07040968723595142
color:
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  brandStrength: 0.5604153785388917
  lightness: 0.2034840672276914
  saturation: 0.8255986443255097
  rhythmicContrast: 0.48048098338767886
name: Shane Statz
favicon: null
title: Shane Statz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
